import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 11,
    color: '#111827',
    backgroundColor: '#fff',
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 6,
  },
  meta: {
    fontSize: 9,
    color: '#6b7280',
    marginBottom: 18,
  },
  body: {
    fontSize: 11,
    lineHeight: 1.4,
    whiteSpace: 'pre-wrap',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: '#9ca3af',
    borderTop: '1px solid #e5e7eb',
    paddingTop: 10,
    textAlign: 'center',
  },
});

export function NotePDF(props: {
  title: string;
  content: string;
  createdAt?: string | null;
  updatedAt?: string | null;
  isPublished?: boolean | null;
  publishedAt?: string | null;
}) {
  const metaParts: string[] = [];
  if (props.isPublished && props.publishedAt) metaParts.push(`Published: ${new Date(props.publishedAt).toLocaleString()}`);
  if (props.updatedAt) metaParts.push(`Updated: ${new Date(props.updatedAt).toLocaleString()}`);
  if (props.createdAt) metaParts.push(`Created: ${new Date(props.createdAt).toLocaleString()}`);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View>
          <Text style={styles.title}>{props.title}</Text>
          {metaParts.length > 0 && <Text style={styles.meta}>{metaParts.join(' • ')}</Text>}
          <Text style={styles.body}>{props.content}</Text>
        </View>

        <View style={styles.footer}>
          <Text>Generated by Plaen</Text>
        </View>
      </Page>
    </Document>
  );
}
